# Docs: https://github.com/Azure/functions-action

name: Build and deploy Node.js project to Azure Function App - compliance-api

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # path to your Function App (repo root)
  NODE_VERSION: '20' # Azure Functions v4 supports 18/20

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present

      # Upload the entire workspace (including dist/) so the deploy job uses the built code
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AA31221142EF4081A5928B3EA31B7B0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7620D92421C44480A6373BFA4D2E9DBE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA240E3DD6F4475298D09811663923CD }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'compliance-api'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          respect-funcignore: true # ensures .funcignore is honored
          scm-do-build-during-deployment: false
